AWSTemplateFormatVersion: '2010-09-09'
    
Resources:
  elasticSearchApplication:
    Type: AWS::ElasticBeanstalk::Application #https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-beanstalk.html
    Properties:
      ApplicationName: ElasticSearchCluster
      Description: EB ElasticSearchCluster
  elasticSearchApplicationVersion:
    Type: AWS::ElasticBeanstalk::ApplicationVersion
    Properties:
      ApplicationName:
        Ref: elasticSearchApplication
      Description: elasticSearchApplication Version
      SourceBundle:
        S3Bucket: mys3bucketforeb
        S3Key: deploy.zip
  elasticSearchConfigurationTemplate:
    Type: AWS::ElasticBeanstalk::ConfigurationTemplate
    Properties:
      ApplicationName:
        Ref: elasticSearchApplication
      Description: elasticSearchApplication Configuration Template
      OptionSettings: # Options located here: https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/command-options-general.html#command-options-general-ec2vpc
      - Namespace: aws:autoscaling:asg
        OptionName: MinSize
        Value: '1'
      - Namespace: aws:autoscaling:asg
        OptionName: MaxSize
        Value: '1'
      - Namespace: aws:elasticbeanstalk:environment
        OptionName: EnvironmentType
        Value: LoadBalanced
      - Namespace: aws:autoscaling:launchconfiguration
        OptionName: EC2KeyName
        Value: new-ec2-keys
      - Namespace: aws:elb:loadbalancer # Limit ingress https://stackoverflow.com/questions/41453302/is-it-possible-to-limit-inbound-ingress-access-to-a-load-balancer-to-a-source-se
        OptionName: SecurityGroups
        Value: !ImportValue 'LoadBalancerSecurityGroupId'
      - Namespace: aws:elb:loadbalancer
        OptionName: ManagedSecurityGroup
        Value: !ImportValue 'LoadBalancerSecurityGroupId'
      - Namespace: aws:autoscaling:updatepolicy:rollingupdate
        OptionName: RollingUpdateEnabled
        Value: true
      - Namespace: aws:elasticbeanstalk:command
        OptionName: DeploymentPolicy
        Value: Rolling
      - Namespace: aws:autoscaling:launchconfiguration
        OptionName: InstanceType
        Value: t2.micro
      SolutionStackName: 64bit Amazon Linux 2017.09 v2.8.4 running Docker 17.09.1-ce
  elasticSearchEnvironment:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      ApplicationName:
        Ref: elasticSearchApplication
      Description: elasticSearchApplication Environment
      TemplateName:
        Ref: elasticSearchConfigurationTemplate
      VersionLabel:
        Ref: elasticSearchApplicationVersion
