Description: "Create an S3Bucket."
AWSTemplateFormatVersion: "2010-09-09"
Parameters: 
  BucketName: 
    Description: "Name for the S3 bucket"
    Type: "String"
  
Resources:
  S3Bucket: 
    Type: "AWS::S3::Bucket"
    Properties: 
      AccessControl: Private
      BucketName: !Ref 'BucketName' 
          
Outputs:
  S3BucketSecureURL:
    Value: !Join ['', ['https://', !GetAtt [S3Bucket, DomainName]]]
    Description: Name of S3 bucket to hold website content